check secret

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -17,7 +17,28 @@ jobs:
           node-version: '22'
 
       - name: Install Dependencies
-        run: npm install  
+        run: npm install
+        
+        # Step 4: Check required secrets
+      - name: Check required secrets
+        run: |
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "Error: DOCKERHUB_USERNAME secret is missing!"
+            exit 1
+          fi
+          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
+            echo "Error: DOCKERHUB_TOKEN secret is missing!"
+            exit 1
+          fi
+          if [ -z "${{ secrets.DB_URL }}" ]; then
+            echo "Error: DB_URL secret is missing!"
+            exit 1
+          fi
+          if [ -z "${{ secrets.PORT }}" ]; then
+            echo "Error: PORT secret is missing!"
+            exit 1
+          fi
+
 
       - name: Generate Prisma Client
         run: npx prisma generate
